import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: [
    './components/**/*.{vue,js,ts}',
    './layouts/**/*.{vue,js,ts}',
    './pages/**/*.{vue,js,ts}',
    './app.vue',
  ],
  theme: {
    extend: {
      colors: {
        'primary-container': '#064e3b',
        'on-background': '#121c2a',
        'on-primary-fixed': '#002117',
        'on-surface-variant': '#404944',
        'surface-dim': '#d0dbed',
        'on-primary-container': '#80bea6',
        'primary-fixed': '#b0f0d6',
        'surface-container': '#e6eeff',
        'error': '#ba1a1a',
        'on-surface': '#121c2a',
        'on-primary': '#ffffff',
        'tertiary': '#2c2f30',
        'inverse-on-surface': '#eaf1ff',
        'on-secondary-fixed-variant': '#763300',
        'secondary-fixed-dim': '#ffb68e',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#b0b2b4',
        'secondary': '#9b4500',
        'background': '#f8f9ff',
        'primary-fixed-dim': '#95d3ba',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#191c1e',
        'outline-variant': '#bfc9c3',
        'surface': '#f8f9ff',
        'surface-tint': '#2b6954',
        'secondary-container': '#fd8a42',
        'on-secondary-fixed': '#331200',
        'surface-bright': '#f8f9ff',
        'surface-container-highest': '#d9e3f6',
        'on-error': '#ffffff',
        'secondary-fixed': '#ffdbca',
        'tertiary-fixed': '#e1e2e4',
        'outline': '#707974',
        'inverse-surface': '#27313f',
        'primary': '#003527',
        'error-container': '#ffdad6',
        'surface-container-low': '#eff4ff',
        'tertiary-container': '#424547',
        'tertiary-fixed-dim': '#c5c6c8',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#682c00',
        'on-tertiary-fixed-variant': '#444749',
        'surface-container-high': '#dee9fc',
        'on-primary-fixed-variant': '#0b513d',
        'surface-variant': '#d9e3f6',
        'inverse-primary': '#95d3ba',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'container-max': '1440px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '1.5', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
} satisfies Config
